services:
  todo-std:
    build: ./
    command: ./todo-std
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DB_PASSWORD: ${POSTGRES_PASSWORD}
  db:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    ports:
      - 5436:5432

volumes:
  postgres_data:
